### ISSUE TITLE
Choice of lattice type for equation of state

### ISSUE THREAD

**Issue by chrisewolf** [dalcorso/thermo_pw#1]
Dear all,

I am curious why the equation of state fitting uses "hex" lattices despite the input lattice being sc, fcc, bcc, ..

For example09 (silicon, ibrav=2) the corresponding control file for the EOS fit is

```
au
hex
4
energy_files/output_ev.dat
energy_files/output_ev.dat.ev.out

```
If I am not mistaken this has an effect on the value of for example the bulk modulus?

Thanks in advance for your help!

With best regards,
Chris

**Comment by dalcorso** [comment]
hex is used in all cases in which you fit volume versus energy data. sc, fcc  or bcc require lattice constant energy data.
