### ISSUE TITLE
Crash in electrons_scf_tpw for magnetic systems

### ISSUE THREAD

**Issue by martok** [dalcorso/thermo_pw#7]
`report_mag` in qe-7.0 has an optional parameter that requires the explicit interface to be imported, otherwise the compiler leaves the argument unset, which leads to segfaults at:
https://github.com/dalcorso/thermo_pw/blob/aa03c6948340edb7692a8c2664ca2deaddd0da09/qe/electrons_tpw.f90#L917

This patch fixes the problem for me:
```patch
diff --git a/qe/electrons_tpw.f90 b/qe/electrons_tpw.f90
index 1d13d88..949bd57 100644
--- a/qe/electrons_tpw.f90
+++ b/qe/electrons_tpw.f90
@@ -442,6 +442,7 @@ SUBROUTINE electrons_scf_tpw ( printout, exxen )
   USE wvfct_gpum,           ONLY : using_et
   USE scf_gpum,             ONLY : using_vrs
   USE device_fbuff_m,             ONLY : dev_buf, pin_buf
+  USE pwcom,                ONLY : report_mag
   !
   IMPLICIT NONE
   !
```

**Comment by dalcorso** [comment]
Thank you for reporting. I corrected the git version.

**Comment by martok** [comment]
Great, thank you! :+1:
