### ISSUE TITLE
About the piezoelectric tensor

### ISSUE THREAD

**Issue by tsiayigong** [dalcorso/thermo_pw#8]
Dear thermo_pw developers,
   Hello, if you can provide some examples for me to compute the piezoelectric tensor with `what=scf_piezoelectric_tensor` or `what=mur_lc_piezoelectric_tensor`? 

JYG

**Comment by dalcorso** [comment]
This option is not active yet.

Andrea

Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
From: Tsia-Yi Gong ***@***.***>
Sent: Sunday, July 24, 2022 8:00:51 AM
To: dalcorso/thermo_pw ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dalcorso/thermo_pw] About the piezoelectric tensor (Issue #8)


Dear thermo_pw developers,
Hello, if you can provide some examples for me to compute the piezoelectric tensor with what=scf_piezoelectric_tensor or what=mur_lc_piezoelectric_tensor?

JYG
