### ISSUE TITLE
dE0s is positive which should never happen

### ISSUE THREAD

**Issue by dishu1** [dalcorso/thermo_pw#9]
Hello. I'm trying to calculate elastic constants of a series of organic crystals and here's what I get. It seems that the vc-relax routine is limited by 20 iterations maximum (which IMHO is unreasonable). What is the way around?

 ```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     task #         0
     from bfgs : error #         1
     dE0s is positive which should never happen
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
[Input+Logs.zip](https://github.com/dalcorso/thermo_pw/files/10670708/Input%2BLogs.zip)

**Comment by KoKoMi-Y** [comment]
Did you solve the problem？

**Comment by dalcorso** [comment]
This is a problem in atomic relaxation. Probably your threshold on forces is too small.
